- name: Install Required Build Packages/Tools on RHEL
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - gd
      - gd-devel
      - make
      - net-snmp
      - httpd
      - php
      - unzip
      - wget
      - postfix
      - openssl-devel
    state: present
  when: ansible_os_family == "RedHat"


- name: download Nagios
  get_url: 
    url: "https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz"
    dest: "{{ download_dir }}/{{ nagiossrc }}.tar.gz"

- name: unpack Nagios source files
  shell: cd {{ download_dir }} && tar -xzvf {{ nagiossrc }}.tar.gz creates={{ download_dir }}/{{ nagiossrc }}

- name: configure Nagios
  shell: cd {{download_dir}}/nagioscore-nagios-4.4.6 && ./configure --with-command-group={{ monitoring_command_group }} -with-command-user={{ monitoring_user }} --with-nagios-user={{ monitoring_user }} --with-nagios-group={{ monitoring_command_group }} creates={{ download_dir }}/{{ nagiossrc }}/Makefile
  
- name: make all
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make all creates={{ download_dir }}/{{ nagiossrc }}/base/nagios

- name: make install
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install creates=/usr/local/nagios/bin/nagios

- name: make install-config
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install-config creates=/usr/local/nagios/etc/nagios.cfg

- name: make install-commandmode
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install-commandmode creates=/usr/local/nagios/var/rw

- name: make install-devel
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install-devel creates=/usr/local/nagios/include/nagios/nagios.h

- name: make install-webconf
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install-webconf creates={{ with_httpd_conf }}/nagios.conf
  notify: restart apache

- name: make install-init
  shell: cd {{ download_dir }}/nagioscore-nagios-4.4.6 && make install-init creates=/etc/init.d/nagios

- name: create {{ monitoring_command_group }} group
  group: name={{ monitoring_command_group }} state=present

- name: create {{ monitoring_user }} user
  user: name={{ monitoring_user }} state=present groups={{ monitoring_command_group }}

- name: add apache user to {{ monitoring_command_group }} group
  user: name={{ apache_user }} state=present groups={{ monitoring_command_group }}

- name: Set up Apache user for Nagios
  command: htpasswd -b -c /usr/local/nagios/etc/htpasswd.users nagiosadmin password

- name: Restart Apache service
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - httpd

- name: get plugins
  get_url: url={{ pluginsurl }} dest={{ download_dir }}/{{ pluginssrc }}.tar.gz

- name: unpack plugin source files
  shell: cd {{ download_dir }} && tar -xzvf {{ pluginssrc }}.tar.gz creates={{ download_dir }}/{{ pluginssrc }}

- name: configure plugins
  shell: cd {{ download_dir }}/{{ pluginssrc }} && ./configure --with-nagios-user={{ monitoring_user }} --with-nagios-group={{ monitoring_command_group }} creates={{ download_dir }}/{{ pluginssrc }}/Makefile

- name: make plugins
  shell: cd {{ download_dir }}/{{ pluginssrc }} && make creates={{ download_dir }}/{{ pluginssrc }}/plugins/check_ping

- name: make install plugins
  shell: cd {{ download_dir }}/{{ pluginssrc }} && make install creates=/usr/local/nagios/libexec/check_ping

- name: install nrpe plugin for nagios
  yum: name=nagios-plugins-nrpe state=present

- name: copy check_nrpe plugin in nagios libexec
  copy: remote_src=True src=/usr/lib64/nagios/plugins/check_nrpe dest=/usr/local/nagios/libexec/check_nrpe  mode=0755
  ignore_errors: true

- name: Start and enable Nagios and NRPE services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nagios

-  name: Ensure the directory /usr/local/nagios/etc/servers exists
   file:
    path: /usr/local/nagios/etc/servers
    state: directory
    mode: '0755'  
  
- name: Ensure /usr/local/nagios/etc/servers/ directory exists
  file:
    path: /usr/local/nagios/etc/servers/
    state: directory
    mode: '0755'

- name: Uncomment line 51 in nagios.cfg
  become: yes
  replace:
    path: /usr/local/nagios/etc/nagios.cfg
    regexp: '^#cfg_dir=/usr/local/nagios/etc/servers '
    replace: 'cfg_dir=/usr/local/nagios/etc/servers '  

- name: Create Nagios config file for remote host
  template:
    src: templates/clientname.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname.cfg
    mode: '0644'

- name: Create Nagios config file for remote host
  template:
    src: templates/clientname2.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname2.cfg
    mode: '0644'

- name: Create Nagios config file for remote host
  template:
    src: templates/clientname3.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname3.cfg
    mode: '0644'
  
- name: Create Nagios config file for remote host
  template:
    src: templates/clientname4.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname4.cfg
    mode: '0644'

- name: Create Nagios config file for remote host
  template:
    src: templates/clientname5.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname5.cfg
    mode: '0644'

- name: Create Nagios config file for remote host
  template:
    src: templates/clientname6.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname6.cfg
    mode: '0644'
  
- name: Create Nagios config file for remote host
  template:
    src: templates/clientname7.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname7.cfg
    mode: '0644'
  
- name: Create Nagios config file for remote host
  template:
    src: templates/clientname8.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname8.cfg
    mode: '0644'
  
- name: Create Nagios config file for remote host
  template:
    src: templates/clientname9.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname9.cfg
    mode: '0644'
  
- name: Create Nagios config file for remote host
  template:
    src: templates/clientname10.cfg.j2
    dest: /usr/local/nagios/etc/servers/clientname10.cfg
    mode: '0644'